### ISSUE TITLE
Edital 16/2021 - CENIC

### ISSUE THREAD

**Issue by luannaalves** [EscolaDeSaudePublica/SACS#295]
### Objetivo
**Como** candidato de processo seletivo
**Quando** acessar o endereço de inscrições do Edital nº 16/2021 - CENIC
**Então** quero realizar minha inscrição e participar de todas as etapas das quais for classificado dentro do processo.

### Escopo
O edital precisa estar no ar no dia 03/09/2021 conforme especificado.

<table border="1" align="center">
<thead>
  <tr>
    <td colspan="2"><strong>Acompanhamento do Edital</strong></td>
  </tr>
</thead>
<body>
  <tr>
    <td>GitHub</td>
    <td><a href="https://github.com/EscolaDeSaudePublica/SACS/projects/44">clique aqui</a></td>
  </tr>
  <tr>
    <td>Trello</td>
      <td><a href="https://trello.com/b/9FT7DYFB/gt-cesp">clique aqui</a></td>
  </tr>
  <tr>
    <td>Página da ESP-CE</td>
    <td><a href="">aguardando</a></td>
  </tr>
  <tr>
    <td>Endereço do Sistema</td>
    <td><a href="">aguardando</a></td>
  </tr>
</body>
</table>

**Critérios de Aceitação:** 
- [x] Edital analisado (calendário, etapas, pontuação, etc) 
- [x] Edital criado no Sisweb/SIGRH :point_left:
- [x] Criada a estrutura de banco
- [ ] Implementado e testado
- [ ] Publicado 

<table border="1" align="center">
<thead>
  <tr>
    <td colspan="2"><strong>Links das Issues dos Critérios de Aceitação</strong></td>
  </tr>
</thead>
<body>
  <tr>
    <td>Análise do edital (calendário, etapas, pontuação, etc)</td>
    <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/296">clique aqui</a></td>
  </tr>
  <tr>
    <td>Criar o edital do Sisweb/SIGRH</td>
    <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/297">clique aqui</a></td>
  </tr>
  <tr>
    <td>Criar a estrutura de banco</td>
   <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/298">clique aqui</a></td>
  </tr>
  <tr>
    <td>Implementar e testar</td>
     <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/299">clique aqui</a></td>
  </tr>
  <tr>
    <td>Publicar o edital</td>
   <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/300">clique aqui</a></td>
  </tr>
</body>
</table>
